name: Deploy to GitHub Pages

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: Development

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Since you don't have requirements.txt, no additional dependencies are needed

      - name: Build and test
        run: |
          # Add commands here to build and test your Flask app
          # For example:
          # python manage.py test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
